### ISSUE TITLE
Re-implement chaining searchers

### ISSUE THREAD

**Issue by KyouyamaKazusa0805** [KyouyamaKazusa0805/Sudoku#549]
There is a thing I have to do now - re-implement chaining APIs to support grouped nodes.

From the year 2019 (beginning with this repository), I have chosen the algorithm and copied the basic implementation for Sudoku Explainer.

This algorithm has been lived for 5 years. I must say this algorithm is very good one that always makes me satisfied.

"But ~~Xiaolu~~ Sunnie", you might say, "Why you didn't use your own algorithm from the start?"

A rough problem is that, I'm not familiar with algorithm of chains. I just think that the chaining rule is too hard to implement, keeping a good performance.

I want to challenge this in not few weeks.

---

翻译：

有一个亟待解决的事情 - 我必须要开始重新实现链的 API 来支持区块节点了。

从 2019 年开始（梦开始的地方），我就选择了一个 Sudoku Explainer 的基础实现作为我的项目的链的基本处理算法。

这个算法在这个项目里存在了 5 年之久。我不得不说这个算法我一直都觉得不错。

不过你可能会问我~~小鹿~~：“为啥你不最开始就使用你自己的算法呢？”

有一个棘手的问题。我根本不熟悉链的算法。我就觉得这玩意儿有点难实现，而且要保证良好的性能。

我打算要不了几周之后开始挑战这个玩意儿。

---

To-do list:

- [x] APIs
  - [x] Step searcher types
    - [x] `ChainStepSearcher`
    - [x] `GroupedChainStepSearcher`
    - [x] `MultipleForcingChainsStepSearcher`
    - [x] `FinnedChainStepSearcher`
    - [x] `BlossomLoopStepSearcher`
    - [x] `MultipleForcingChainsStepSearcher`
    - [x] `UniqueRectangleMultipleForcingChainsStepSearcher`
    - [x] `BivalueUniversalGraveMultipleForcingChainsStepSearcher`
    - [x] `DynamicForcingChainsStepSearcher`
  - [x] Driver type: `ChainingDriver`
  - [x] Data types:
    - [x] Abstract type `ChainOrLoop`
    - [x] AIC chains type `Chain`, `Loop`
    - [x] Forcing chains type `StrongForcingChain` and `WeakForcingChain`
  - [x] Algorithm
    - [x] Basic sorting rule
    - [x] Sort keys
      - [x] Property implementation
      - [x] #663
    - [x] #664 (Hash code calculation on chains and loops)
    - [x] Searching algorithm: BFS ~~DFS~~
    - [x] Caching
      - [x] L1 Cache (Cache strong and weak links before chaining)
      - [ ] #702 (Cache strong and weak links before the first step using chaining searcher)
    - [x] Linking rule
      - [x] #682
      - [x] Only inside a locked candidates
      - [x] Only inside a house
      - [x] All possible links will be matched
  - [x] Step type
  - [x] Duplicate checking
    - [x] Hash code support
    - [x] Equality comparison support
  - [x] Nodes
    - [x] Single candidate node
    - [x] Locked candidates node
    - [x] Almost Locked Sets node
    - [x] #683
    - [x] Almost Unique Rectangle node
    - [x] Almost Avoidable Rectangle node
    - [x] #684
  - [x] Other works
    - [x] Deprecated APIs removing
    - [x] #680
    - [x] #679
    - [x] #678
    - [x] #677
    - [x] #676
    - [ ] #546
    - [x] #668 (storing strong and weak links found, but `static` fields)
    - [x] #669
    - [x] #673
    - [x] #729
      - [x] #730
    - [x] #743
  - [x] Bug fixes
- [x] Specialized chain types
  - [x] #671
- [x] Chaining rules
  - [x] #661
  - [x] #667
  - [x] #670 (A kind of Dynamic Continuous Nice Loop, Chinese: 绽放环)
  - [x] #674
  - [x] #662
  - [x] #665
  - [x] #689 (Chinese: 牺牲, [link](https://www.bilibili.com/video/BV1dY4y1T7A6/))
  - [x] #690 (Chinese: 逆否命题)
  - [x] #681
- [x] Dynamic Chaining rules
  - [x] API Modifications
    - [x] #740
  - [x] Sequential Dynamic Chaining (Whip, Braid)
    - [x] #737
    - [x] #738
  - [x] Dynamic Forcing Chains
    - [x] Dynamic Cell Forcing Chains
    - [x] Dynamic Region Forcing Chains
    - [x] Dynamic Contradiction Forcing Chains
    - [x] Dynamic Double Forcing Chains

**Comment by SunnieShine** [comment]
Finish for the first phase.
